In [59]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [60]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [61]:
df= pd.read_csv('/content/drive/MyDrive/ML-SelfStudyCode/Titanic-Dataset.csv')
df.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

In [62]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [63]:
# Fill missing values
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.isnull().sum()

/tmp/ipykernel_15963/1741053070.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)
/tmp/ipykernel_15963/1741053070.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [64]:
df_encoder = pd.get_dummies(df, columns=['Sex', 'Embarked'])

In [65]:
x= df_encoder.drop('Survived', axis=1).values
y= df_encoder['Survived'].values

x_train, x_test, y_train, y_test= train_test_split(x, y, test_size=0.2, random_state=42)

In [83]:
x_test

array([[ 0.81303367, -0.09263364,  0.37992316, ...,  2.16702561,
        -0.30335547, -1.68779402],
       [-0.40055118,  0.13815631, -0.47072241, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [ 0.81303367, -0.7080735 , -0.47072241, ..., -0.46146201,
        -0.30335547,  0.59248936],
       ...,
       [ 0.81303367,  0.67666619,  0.37992316, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [-0.40055118, -0.93886345, -0.47072241, ..., -0.46146201,
        -0.30335547,  0.59248936],
       [ 0.81303367, -1.93895323,  0.37992316, ..., -0.46146201,
        -0.30335547,  0.59248936]])

In [84]:
y_test

array([1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 1])

In [66]:
scaler= StandardScaler()
x_train= scaler.fit_transform(x_train)
x_test= scaler.transform(x_test)

In [67]:
# start from sigmod
def sigmoid(z):
  return 1/ (1 + np.exp(-z))

In [68]:
# test sigmiod
print(sigmoid(0))
print(sigmoid(100))
print(sigmoid(-100))

0.5
1.0
3.7200759760208356e-44

In [69]:
# initialize weight / z parameters
def initialize_params(n):
  w= np.zeros(n)
  b= 0.0
  return w,b

In [70]:
w,b= initialize_params(5)
print(w)
print(b)

[0. 0. 0. 0. 0.]
0.0

In [71]:
# forward pass
def forward(X, w, b):
  z= np.dot(X, w) + b
  y_hat= sigmoid(z)
  return y_hat

In [72]:
# loss function
def loss(y, y_hat):
  m = len(y)
  loss = - np.mean(y*np.log(y_hat) + (1-y)*np.log(1-y_hat))
  return loss

In [73]:
# backward pass, gradient descent
def backward(X, y, y_hat):
  m= len(y)
  dw = (1/m)*np.dot(X.T, (y_hat - y))
  db = (1/m)*np.sum(y_hat - y)
  return dw, db

In [74]:
# train
def train(X, y, learning_rate=0.01, epochs=100):
  w,b = initialize_params(X.shape[1])

  for epoch in range(epochs):
    y_hat = forward(X, w, b)
    loss_value = loss(y, y_hat)
    dw,db = backward(X, y, y_hat)

    # update weights
    w= w - learning_rate * dw
    b = b- learning_rate * db

    if epoch%100 == 0:
      print(f"Epoch: {epoch}, Loss: {loss_value}")

  return w,b

In [75]:
def predict(X, w, b):
  y_hat = forward(X, w, b)
  y_pred = np.where(y_hat > 0.5, 1, 0)
  return y_pred

In [78]:
train(x_train, y_train)

Epoch: 0, Loss: 0.6931471805599453

(array([-0.1252521 , -0.02284977, -0.02692176,  0.02030467,  0.08732578,
         0.20277801, -0.20277801,  0.05490979, -0.00257904, -0.04600204]),
 np.float64(-0.10945565252282194))

In [86]:
predict(x_test[3], w, b)

array(1)